name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: linux-x86_64
            artifact: durmanpass_${{ github.ref_name }}_amd64.AppImage.tar.gz
          - os: windows-latest
            target: windows-x86_64
            artifact: durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip
          - os: macos-latest
            target: darwin-x86_64
            artifact: durmanpass_${{ github.ref_name }}_x64.dmg

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Build Tauri app
        run: |
          npm install
          npm run tauri build -- --target ${{ matrix.target }}
      - name: Sign binary
        env:
          MINISIGN_PRIVATE_KEY: ${{ secrets.MINISIGN_PRIVATE_KEY }}
        run: |
          curl -L -o minisign.tar.gz https://github.com/jedisct1/minisign/releases/download/0.10/minisign-0.10.tar.gz
          tar -xzf minisign.tar.gz
          cd minisign-0.10
          make
          ./minisign -Sm ../src-tauri/target/release/bundle/${{ matrix.artifact }} -x ../${{ matrix.artifact }}.sig
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: src-tauri/target/release/bundle/${{ matrix.artifact }}
      - name: Upload signature
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}.sig
          path: ${{ matrix.artifact }}.sig

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Generate latest.json
        run: |
          echo '{
            "version": "${{ github.ref_name }}",
            "notes": "Release notes for ${{ github.ref_name }}",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {
              "windows-x86_64": {
                "signature": "$(cat artifacts/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip.sig)",
                "url": "https://github.com/DurmanPass/Durman-Desktop/releases/download/${{ github.ref_name }}/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip"
              },
              "darwin-x86_64": {
                "signature": "$(cat artifacts/durmanpass_${{ github.ref_name }}_x64.dmg/durmanpass_${{ github.ref_name }}_x64.dmg.sig)",
                "url": "https://github.com/DurmanPass/Durman-Desktop/releases/download/${{ github.ref_name }}/durmanpass_${{ github.ref_name }}_x64.dmg"
              },
              "linux-x86_64": {
                "signature": "$(cat artifacts/durmanpass_${{ github.ref_name }}_amd64.AppImage.tar.gz/durmanpass_${{ github.ref_name }}_amd64.AppImage.tar.gz.sig)",
                "url": "https://github.com/DurmanPass/Durman-Desktop/releases/download/${{ github.ref_name }}/durmanpass_${{ github.ref_name }}_amd64.AppImage.tar.gz"
              }
            }
          }' > latest.json
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip
            artifacts/durmanpass_${{ github.ref_name }}_x64.dmg/durmanpass_${{ github.ref_name }}_x64.dmg
            artifacts/durmanpass_${{ github.ref_name }}_amd64.AppImage.tar.gz/durmanpass_${{ github.ref_name }}_amd64.AppImage.tar.gz
            latest.json
          body: "Release notes for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}