name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [windows-x86_64]
        artifact: [durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build Tauri app
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        run: |
          npm install
          npm run tauri build -- --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: src-tauri/target/release/bundle/${{ matrix.artifact }}
      - name: Upload signature
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}.sig
          path: src-tauri/target/release/bundle/${{ matrix.artifact }}.sig

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Generate latest.json
        run: |
          echo '{
            "version": "${{ github.ref_name }}",
            "notes": "Release notes for ${{ github.ref_name }}",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {
              "windows-x86_64": {
                "signature": "$(cat artifacts/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip.sig)",
                "url": "https://github.com/DurmanPass/Durman-Desktop/releases/download/${{ github.ref_name }}/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip"
              }
            }
          }' > latest.json
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip/durmanpass_${{ github.ref_name }}_x64_en-US.msi.zip
            latest.json
          body: "Release notes for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}